[[language]]
name = "rust"
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'

[language-server.ruff]
command = "ruff-lsp"
# [language-server.pyright]
# command = "pyright"

[[language]]
name = "python"
language-servers = [ 
{name = "ruff", only-features = ["format"]}, 
{name = "pyright", except-features = ["format"]} 
]
auto-format = true

